import sqlite3

con = sqlite3.connect("ponto.db")

con.execute("DROP TABLE IF EXISTS REGISTRO")
con.execute("DROP TABLE IF EXISTS COLABORADORES")
print("TABELAS DROPADAS")

con.execute(
    "CREATE TABLE COLABORADORES ("
    "COL_ID INTEGER PRIMARY KEY AUTOINCREMENT,"
    "COL_RG TEXT,"
    "COL_NOME TEXT NOT NULL,"
    "COL_EMAIL TEXT UNIQUE NOT NULL)"
)

con.execute(
    "CREATE TABLE REGISTRO ("
    "REG_ID INTEGER PRIMARY KEY AUTOINCREMENT,"
    "COL_ID INTEGER,"
    "REG_NOME TEXT NOT NULL,"
    "REG_DATA DATE UNIQUE NOT NULL,"
    "FOREIGN KEY(COL_ID) REFERENCES artist(COL_ID))"
)
print("TABELAS CRIADAS")

con.close()
