CREATE TABLE COLABORADORES (COL_ID INTEGER PRIMARY KEY AUTOINCREMENT,COL_RG TEXT, COL_NOME TEXT NOT NULL,COL_EMAIL TEXT UNIQUE NOT NULL);

CREATE TABLE REGISTRO (
    REG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COL_ID INTEGER,
    REG_NOME TEXT NOT NULL,
    REG_DATA DATE UNIQUE NOT NULL,
    FOREIGN KEY(COL_ID) REFERENCES artist(COL_ID)
    );

SELECT REGISTRO.REG_DATA, COLABORADORES.COL_MATRICULA, COLABORADORES.COL_NOME FROM REGISTRO INNER JOIN COLABORADORES ON REGISTRO.COL_ID = COLABORADORES.COL_ID ORDER BY REGISTRO.REG_DATA DESC
